# Generated by Django 4.0.2 on 2022-02-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateField()),
                ('deleted_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateField()),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('car_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60, verbose_name='User Name')),
                ('first_reg', models.DateField()),
                ('odometer', models.IntegerField()),
                ('created_at', models.DateField()),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('car_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.carbrand')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.carmodel')),
            ],
        ),
    ]
