# Generated by Django 4.0.2 on 2022-02-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
    ]
