# Generated by Django 4.0.2 on 2022-02-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='deleted_at',
            field=models.DateField(),
        ),
    ]
