# Generated by Django 4.0.2 on 2022-02-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbrand', '0002_alter_carbrand_created_at_alter_carbrand_deleted_at'),
        ('carmodel', '0002_alter_carmodel_created_at_alter_carmodel_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carbrand.carbrand'),
        ),
    ]
